### ISSUE TITLE
Firebase auth issue in console

### ISSUE THREAD

**Issue by utsavprabhakar** [bobangajicsm/react-portfolio-website#15]
I have cloned the project and run the server. Getting a white screen and i get this in console
```
bootstrap:27 Uncaught FirebaseError: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (assert.ts:128:1)
    at _assert (assert.ts:153:1)
    at register.ts:67:1
    at Component.instanceFactory (register.ts:90:1)
    at Provider.getOrInitializeService (provider.ts:318:1)
    at Provider.initialize (provider.ts:242:1)
    at initializeAuth (initialize.ts:66:1)
    at getAuth (index.ts:44:1)
    at ./src/firebase.js (firebase.js:18:1)
    at options.factory (react refresh:6:1)
```

Can anyone provide me some documentation for how to setup this firebase since i can see that the firebase.js contains empty API keys etc. Thanks!

**Comment by utsavprabhakar** [comment]
Never mind, it was this simple: https://medium.com/firebase-developers/how-to-setup-firebase-authentication-with-react-in-5-minutes-maybe-10-bb8bb53e8834

For readers, firebase UI seems to be updated but the above article will provide you a brief overview of what to do. It should take less than 5 mins to setup.
